import asyncio
import os
import sys
from datetime import date
from sqlalchemy import select
import pandas as pd

# Add project root to path
sys.path.append(os.getcwd())

from app.database import db_manager
from app.services.rule_engine_service import RuleEngineService
from app.services.ranking_service import RankingService
from app.models.tag_management import StockTagRelation, StockTagInfo
from app.models.stock_daily import StockScoreResult, StockDaily

async def verify_603601_final():
    stock_code = "603601"
    # User requirements: check around 2025-11-28
    check_dates = [
        date(2025, 11, 28),
        date(2025, 11, 29), # Add weekend/gap check? Market usually closed, but let's stick to user request "consecutive 5 trading days"
        # Assuming trading days. Let's list a few days around it.
        date(2025, 12, 1), 
        date(2025, 12, 2),
        date(2025, 12, 3),
        date(2025, 12, 4),
        date(2025, 12, 5)
    ]
    
    print(f"\n====== Final Acceptance Verification for {stock_code} ======")
    
    # 1. Data Verification
    async with db_manager.get_session() as session:
        print("\n[1] Verifying Data Integrity...")
        stmt = select(StockDaily).where(
            StockDaily.code == stock_code,
            StockDaily.trade_date >= date(2025, 11, 20),
            StockDaily.trade_date <= date(2025, 12, 10)
        ).order_by(StockDaily.trade_date)
        res = await session.execute(stmt)
        data = res.scalars().all()
        
        if not data:
            print("❌ No data found! Please ensure data is loaded.")
            return

        print(f"✅ Found {len(data)} records from {data[0].trade_date} to {data[-1].trade_date}")
        
    # 2. Logic Verification (Tags & Scores)
    print("\n[2] Verifying Logic (Tags & Scores)...")
    rule_engine = RuleEngineService(db_manager)
    
    results = []
    
    for d in check_dates:
        # Check if it is a trading day (exists in data)
        # For simplicity, we just try to run. If no data, it might skip or return 0.
        
        print(f"  > Processing {d}...")
        
        # A. Trigger Scoring (Backend Logic)
        # This calculates score based on tags and other rules, saves to StockScoreResult
        # It handles its own session/transaction, so we call it outside of our session block to avoid locks
        try:
            await rule_engine.calculate_daily_scores(target_date=d, stock_code=stock_code, force=True)
        except Exception as e:
            print(f"    ⚠️ Calculation skipped/failed for {d}: {e}")
            results.append({
                "date": d,
                "tags": [],
                "score": "Error",
                "details": str(e)
            })
            continue
        
        # B. Check Results (New Session)
        async with db_manager.get_session() as session:
            # Check Tags (generated by calculate_daily_scores -> volume_analysis)
            tag_stmt = select(StockTagInfo.name).join(StockTagRelation).where(
                StockTagRelation.stock_code == stock_code
            )
            tag_res = await session.execute(tag_stmt)
            tags = tag_res.scalars().all()
            
            # Get Score
            score_stmt = select(StockScoreResult).where(
                StockScoreResult.code == stock_code, # CORRECTED field name
                StockScoreResult.trade_date == d
            )
            score_res = await session.execute(score_stmt)
            score_rec = score_res.scalar_one_or_none()
            
            results.append({
                "date": d,
                "tags": tags,
                "score": float(score_rec.total_score) if score_rec else 0.0,
                "details": score_rec.rule_scores if score_rec else {} # Changed to rule_scores (JSON field)
            })
        
    # Print Detailed Report
    print("\n[3] Daily Analysis Report:")
    print(f"{'Date':<12} | {'Tags':<50} | {'Score':<8} | {'Details'}")
    print("-" * 120)
    for r in results:
        tags_str = ",".join(r['tags'])
        # Truncate details for display
        details_str = str(r['details'])
        if len(details_str) > 50:
            details_str = details_str[:47] + "..."
            
        print(f"{r['date']} | {tags_str:<50} | {str(r['score']):<8} | {details_str}")

    # 3. Ranking Verification
    target_rank_date = date(2025, 12, 5)
    print(f"\n[4] Verifying Ranking on {target_rank_date}...")
    
    async with db_manager.get_session() as session:
        ranking_service = RankingService(session)
        # Assuming get_total_score_ranking returns list of dicts
        rankings = await ranking_service.get_total_score_ranking(target_date=target_rank_date, limit=50)
        
        my_entry = next((x for x in rankings if x['code'] == stock_code), None)
        if my_entry:
            print(f"✅ Rank: {my_entry.get('ranking')} | Score: {my_entry.get('total_score')}")
            if int(my_entry.get('ranking', 999)) <= 20:
                print("✅ Requirement Met: Top 20")
            else:
                print(f"❌ Requirement Failed: Rank {my_entry.get('ranking')} > 20")
        else:
            print("❌ Not in Top 50")
            if rankings:
                print(f"Top 1: {rankings[0]}")

if __name__ == "__main__":
    asyncio.run(verify_603601_final())
